server:
  port: ${OTP_PORT:8082}
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: otp
  datasource:
    url: jdbc:postgresql://localhost:5433/mentoring
    username: dev
    password: Ab123456
    hikari:
      schema: otp
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  liquibase:
    change-log: ./db/changelog/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      acks: all
    consumer:
      group-id: otp-group

otp:
  kafka:
    send-otp-in:
      enabled: true
      topic: Send.Otp.IN.V1
    send-otp-out:
      enabled: true
      topic: Send.Otp.OUT.V1